/**
 * 左侧菜单数据
 */
import Vue from 'vue';
import { PersistedAction, PersistedConfig, STORAGE_TYPE } from 'vue-simple';

import router from '../router';
import ApiConf from '../conf/api.conf';
import UrlMap from '../router/UrlMap';
import Frame from '../reportCenter/frame/Frame';

PersistedConfig.batch([
  // { type: `shop/${types.SET_PAGE_CONFIG}`, storage: STORAGE_TYPE.localStorage },
  { type: 'menu/setMenuList', storage: STORAGE_TYPE.sessionStorage, expire: 600 } // 10分钟过期重新取
]);

const State = {
  loaded: false,
  menuList: {}
};

const Getters = {
  menuList: state => state.menuList
};

// 同步立即更新
const MutAtions = {
  setLoaded(state, params) {
    state.loaded = params;
  },
  /**
   * 设置新的用户数据
   * @param state
   * @param params
   */
  setMenuList(state, params) {
    state.menuList = params.data;

    // 动态设置路由配置
    Vue.$dynamicRouter.setUrlMap(UrlMap);
    Vue.$dynamicRouter.base = { path: '/frame', component: Frame };
    const map = Vue.$dynamicRouter.parse(state.menuList);
    Vue.$dynamicRouter.install(router, map);
  }
};
// 异步请求数据
const Actions = {
  persist: PersistedAction,
  getMenuList({ dispatch, rootGetters }) {
    return dispatch('persist', {
      type: 'menu/setMenuList',
      getData() {
        return new Promise((resolve, reject) => {
          // 只有在登录成功进入，或者F5刷新浏览器时才重新请求菜单数据
          // 正常单页应用操作下跳转路由，菜单数据不会丢失，所以不再重复请求
          // if (!store.getters['menu/setMenuList']) {
          // 取用户 state 数据进行提交
          const userinfo = rootGetters['tokenInfo/userinfo'];
          const params = {
            user_id: userinfo.user_id, // 4
            type: userinfo.type // 'EMPLOYEE'
          };

          // 真实菜单数据请求
          Vue.$api.post({ getway: ApiConf.user.$getway, api: ApiConf.user.menuLoadMenusByUser }, params).then(response => {
            let result = response.data;
            if (result.code === '10000') {
              // const menuListLocal = {
              //   code: '10000',
              //   msg: 'OK',
              //   sub_msg: null,
              //   data: [
              //     {
              //       id: 100,
              //       name: '运营报表',
              //       description: '运营报表',
              //       url: '/operatingReport',
              //       icon: 'operationreport',
              //       is_root: 1,
              //       is_leaf: 0,
              //       parent_id: 0,
              //       level: 1,
              //       sort: 2,
              //       is_new: 1,
              //       is_star: 0,
              //       platform: 'shopper-center',
              //       is_valid: 1,
              //       is_enter: 0,
              //       invoke_source: 2200,
              //       checked: null,
              //       children: [{
              //         id: 103,
              //         name: '明细汇总',
              //         description: '明细汇总',
              //         url: '/detailsSummary',
              //         icon: 'detailcollect',
              //         is_root: 0,
              //         is_leaf: 0,
              //         parent_id: 100,
              //         level: 2,
              //         sort: 1,
              //         is_new: 1,
              //         is_star: 0,
              //         platform: 'shopper-center',
              //         is_valid: 1,
              //         is_enter: 0,
              //         invoke_source: 2200,
              //         checked: null,
              //         children: [{
              //           id: 108,
              //           name: '营业汇总',
              //           description: '营业汇总',
              //           url: '/businessPool',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 103,
              //           level: 3,
              //           sort: 1,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'shopper-center',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 109,
              //           name: '门店营业汇总',
              //           description: '门店营业汇总',
              //           url: '/storeBusiness',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 103,
              //           level: 3,
              //           sort: 2,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 110,
              //           name: '门店营业汇总报表',
              //           description: '门店营业汇总报表',
              //           url: '/storeTimeBusiness',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 103,
              //           level: 3,
              //           sort: 3,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }]
              //       }, {
              //         id: 105,
              //         name: '数据统计',
              //         description: '数据统计',
              //         url: '/dataStatistics',
              //         icon: 'statisticsdata',
              //         is_root: 0,
              //         is_leaf: 0,
              //         parent_id: 100,
              //         level: 2,
              //         sort: 2,
              //         is_new: 1,
              //         is_star: 0,
              //         platform: 'shopper-center',
              //         is_valid: 1,
              //         is_enter: 0,
              //         invoke_source: 2200,
              //         checked: null,
              //         children: [{
              //           id: 111,
              //           name: '营收统计',
              //           description: '营收统计',
              //           url: '/revenueIncome',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 1,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'shopper-center',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 112,
              //           name: '门店营收统计',
              //           description: '门店营收统计',
              //           url: '/revenueShopIncome',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 2,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 113,
              //           name: '门店营收报表',
              //           description: '门店营收报表',
              //           url: '/shopTimeRevenue',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 3,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 114,
              //           name: '收入统计',
              //           description: '收入统计',
              //           url: '/incomeTotal',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 4,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 900,
              //           name: '挂账统计',
              //           description: '挂账统计',
              //           url: '/accountTotal',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 4,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 115,
              //           name: '门店收入统计',
              //           description: '门店收入统计',
              //           url: '/shopIncome',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 5,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 116,
              //           name: '门店收入报表',
              //           description: '门店收入报表',
              //           url: '/shopTimeIncome',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 6,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 118,
              //           name: '优惠统计',
              //           description: '优惠统计',
              //           url: '/preferentCount',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 8,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 119,
              //           name: '门店优惠统计',
              //           description: '门店优惠统计',
              //           url: '/storePreferent',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 9,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 120,
              //           name: '门店优惠报表',
              //           description: '门店优惠报表',
              //           url: '/storeTimePreferent',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 10,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 121,
              //           name: '退款统计',
              //           description: '退款统计',
              //           url: '/refundCount',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 11,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 122,
              //           name: '门店退款统计',
              //           description: '门店退款统计',
              //           url: '/storeRefundCount',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 12,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 123,
              //           name: '门店退款报表',
              //           description: '门店退款报表',
              //           url: '/storeTimeRefund',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 13,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 156,
              //           name: '收入总账',
              //           description: '收入总账',
              //           url: '/includeLedger',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 14,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 157,
              //           name: '外卖统计',
              //           description: '外卖统计',
              //           url: '/takeoutStatistics',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 15,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 157,
              //           name: '门店商品销售统计',
              //           description: '门店商品销售统计',
              //           url: '/shopGoodsTotle',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 15,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 158,
              //           name: '门店营业日报',
              //           description: '门店营业日报',
              //           url: '/shopBusinessReport',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 15,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 159,
              //           name: '门店结算日报',
              //           description: '门店结算日报',
              //           url: '/shopSettlementReport',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 105,
              //           level: 3,
              //           sort: 15,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }]
              //       }, {
              //         id: 183,
              //         name: '时段分析',
              //         description: '时段分析',
              //         url: '/timeInter',
              //         icon: 'timeinter',
              //         is_root: 0,
              //         is_leaf: 0,
              //         parent_id: 100,
              //         level: 2,
              //         sort: 3,
              //         is_new: 1,
              //         is_star: 0,
              //         platform: 'report-center',
              //         is_valid: 1,
              //         is_enter: 0,
              //         invoke_source: 2200,
              //         checked: null,
              //         children: [{
              //           id: 184,
              //           name: '时段指标分析',
              //           description: '时段指标分析',
              //           url: '/timeIndexAnalysis',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 183,
              //           level: 3,
              //           sort: 1,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'report-center',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 185,
              //           name: '时段对比分析',
              //           description: '时段对比分析',
              //           url: '/timeComparatAnalysis',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 183,
              //           level: 3,
              //           sort: 2,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'report-center',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }]
              //       }]
              //     },
              //     {
              //       id: 101,
              //       name: '商品销售分析',
              //       description: '商品销售分析',
              //       url: '/snalySiscommoditySales',
              //       icon: 'goodssaleanalyze',
              //       is_root: 1,
              //       is_leaf: 0,
              //       parent_id: 0,
              //       level: 1,
              //       sort: 3,
              //       is_new: 1,
              //       is_star: 0,
              //       platform: 'shopper-center',
              //       is_valid: 1,
              //       is_enter: 0,
              //       invoke_source: 2200,
              //       checked: null,
              //       children: [{
              //         id: 104,
              //         name: '属性销售分析',
              //         description: '属性销售分析',
              //         url: '/propertySalesAnalysis',
              //         icon: 'propsaleanalyze',
              //         is_root: 0,
              //         is_leaf: 0,
              //         parent_id: 101,
              //         level: 2,
              //         sort: 1,
              //         is_new: 1,
              //         is_star: 0,
              //         platform: 'shopper-center',
              //         is_valid: 1,
              //         is_enter: 0,
              //         invoke_source: 2200,
              //         checked: null,
              //         children: [{
              //           id: 124,
              //           name: '商品属性日销售分析',
              //           description: '商品属性分析',
              //           url: '/goodsAnalyzeData',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 104,
              //           level: 3,
              //           sort: 1,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'shopper-center',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 125,
              //           name: '商品属性周销售分析',
              //           description: '商品属性分析',
              //           url: '/goodsAnalyzeWeek',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 104,
              //           level: 3,
              //           sort: 2,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'shopper-center',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 126,
              //           name: '商品属性月销售分析',
              //           description: '商品属性分析',
              //           url: '/goodsAnalyzeMonth',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 104,
              //           level: 3,
              //           sort: 3,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'shopper-center',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 127,
              //           name: '商品属性门店分析',
              //           description: '商品属性门店分析',
              //           url: '/goodsStoreAnalyze',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 104,
              //           level: 3,
              //           sort: 4,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }]
              //       }, {
              //         id: 106,
              //         name: '商品销售对比分析',
              //         description: '商品销售对比分析',
              //         url: '/ComparisonAnalysiscommodityAales',
              //         icon: 'goodssalecomparisonanalyze',
              //         is_root: 0,
              //         is_leaf: 0,
              //         parent_id: 101,
              //         level: 2,
              //         sort: 2,
              //         is_new: 1,
              //         is_star: 0,
              //         platform: 'shopper-center',
              //         is_valid: 1,
              //         is_enter: 0,
              //         invoke_source: 2200,
              //         checked: null,
              //         children: [{
              //           id: 128,
              //           name: '商品销售对比分析',
              //           description: '商品销售对比分析',
              //           url: '/goodsSalesAnalysis',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 106,
              //           level: 3,
              //           sort: 1,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'shopper-center',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 129,
              //           name: '门店商品销售对比分析',
              //           description: '门店商品销售对比分析',
              //           url: '/goodsShopAnalysis',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 106,
              //           level: 3,
              //           sort: 2,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }]
              //       }, {
              //         id: 107,
              //         name: '综合分析',
              //         description: '综合分析',
              //         url: '/comprehensiveAnalysis',
              //         icon: 'synthesizeanalyze',
              //         is_root: 0,
              //         is_leaf: 0,
              //         parent_id: 101,
              //         level: 2,
              //         sort: 3,
              //         is_new: 1,
              //         is_star: 0,
              //         platform: 'shopper-center',
              //         is_valid: 1,
              //         is_enter: 0,
              //         invoke_source: 2200,
              //         checked: null,
              //         children: [{
              //           id: 130,
              //           name: '商品销售排行',
              //           description: '商品销售排行',
              //           url: '/goodsRankings',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 107,
              //           level: 3,
              //           sort: 1,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'report-center',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 131,
              //           name: '分类销售排行',
              //           description: '门店营收统计',
              //           url: '/classificationRankings',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 107,
              //           level: 3,
              //           sort: 2,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 158,
              //           name: '商品销售规格属性分析',
              //           description: '商品销售规格属性分析',
              //           url: '/goodsSaleSize',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 107,
              //           level: 3,
              //           sort: 3,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }, {
              //           id: 898,
              //           name: '商品销售综合分析',
              //           description: '商品销售综合分析',
              //           url: '/goodsColligateAnalysis',
              //           icon: '',
              //           is_root: 0,
              //           is_leaf: 1,
              //           parent_id: 107,
              //           level: 3,
              //           sort: 3,
              //           is_new: 1,
              //           is_star: 0,
              //           platform: 'silverbox-admin',
              //           is_valid: 1,
              //           is_enter: 1,
              //           invoke_source: 2200,
              //           checked: null,
              //           children: null
              //         }]
              //       }]
              //     },
              //     {
              //       id: 103,
              //       name: '下载清单',
              //       description: '下载清单',
              //       url: '/tableDownload',
              //       icon: 'download',
              //       is_root: 1,
              //       is_leaf: 0,
              //       parent_id: 0,
              //       level: 1,
              //       sort: 3,
              //       is_new: 1,
              //       is_star: 0,
              //       platform: 'report-center',
              //       is_valid: 1,
              //       is_enter: 1,
              //       invoke_source: 2200,
              //       checked: null,
              //       children: null
              //     },
              //     {
              //       id: 200,
              //       name: '报表数据修复',
              //       description: '报表数据修复',
              //       url: '/repairData',
              //       icon: 'repairdata',
              //       is_root: 1,
              //       is_leaf: 0,
              //       parent_id: 0,
              //       level: 1,
              //       sort: 3,
              //       is_new: 1,
              //       is_star: 0,
              //       platform: 'report-center',
              //       is_valid: 1,
              //       is_enter: 1,
              //       invoke_source: 2200,
              //       checked: null,
              //       children: null
              //     }
              //   ]
              // };

              resolve(result);
              // resolve(menuListLocal);
            }
            else {
              reject(result);
            }
          }).catch(reason => {
            reject(reason);
          });
        });
      }
    });
  }
};

export default {
  namespaced: true,
  strict: true,
  state: State,
  getters: Getters,
  mutations: MutAtions,
  actions: Actions
};
